services:
  - type: web
    name: mit-khoj-backend
    runtime: python
    rootDir: lost_found_backend
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    plan: free
    healthCheckPath: /health
    envVars:
      - key: DB_HOST
        value: maglev.proxy.rlwy.net
      - key: DB_PORT
        value: "35979"
      - key: DB_USER
        value: root
      - key: DB_PASSWORD
        value: KlDhfTbLZwvOrTlfWoFMQTNNJDJXCVnB
      - key: DB_NAME
        value: railway
      - key: JWT_SECRET_KEY
        generateValue: true
      - key: FRONTEND_ORIGINS
        value: "https://ashna3.github.io"
